version: '3.10'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn dompet.wsgi:application -c ./dompet/gunicorn.conf.py
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: