version: '3.10'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn dompet.wsgi:application -c ./dompet/gunicorn.conf.py
    volumes:
      - static_volume:/dompet/static/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    # depends_on:
    #   - db
  # db:
  #   image: postgres:15
  #   volumes:
  #     - /home/cncheong/code/dompet/dump/:/var/lib/postgresql/dump/
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env.db
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/dompet/static/
    ports:
      - 8080:80
    depends_on:
      - api

volumes:
  # postgres_data:
  static_volume:
