[project]
name = "dompet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3==1.35.53",
    "psycopg2-binary==2.9.9",
    "pydantic==2.9.2",
    "python-dotenv>=1.0.0",
]

[project.scripts]
dompet = "dompet:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
