# Generated by Django 4.2.4 on 2023-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('type', models.CharField(blank=True, max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('payment_method', models.CharField(blank=True, max_length=256)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
