# Generated by Django 4.2.4 on 2023-10-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='payment_method',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='type',
            field=models.CharField(max_length=256),
        ),
    ]
