# Generated by Django 4.2.4 on 2023-12-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('location', models.CharField(max_length=256, verbose_name='Location')),
                ('type', models.CharField(max_length=256, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Amount')),
                ('currency', models.CharField(default='MYR', max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(max_length=256, verbose_name='Payment Method')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='Inserted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
