# Generated by Django 4.2.4 on 2023-12-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='location',
            field=models.CharField(blank=True, max_length=256, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='payment_method',
            field=models.CharField(blank=True, max_length=256, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='type',
            field=models.CharField(default='spend', max_length=256, verbose_name='Type'),
        ),
    ]
