# Generated by Django 4.2.4 on 2023-12-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0004_expendituregroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenditure.expendituregroup', verbose_name='Group'),
            preserve_default=False,
        ),
    ]
