# Generated by Django 4.2.4 on 2023-12-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenditure', '0005_expenditure_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expendituregroup',
            name='user',
        ),
        migrations.AddField(
            model_name='expendituregroup',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Inserted At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expendituregroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expendituregroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='expendituregroup',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
